name: CI Cypress

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: https://lojaebac.ebaconline.art.br

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache do Cypress
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Instalar dependências
        run: npm install

      - name: Instalar binário do Cypress
        run: npx cypress install

      - name: Executar testes com Mochawesome
        run: npx cypress run --reporter mochawesome

      - name: Upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: mochawesome-report


